// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import DeleteModalController from "./delete_modal_controller"
application.register("delete-modal", DeleteModalController)

import HamburgerMenuController from "./hamburger_menu_controller"
application.register("hamburger-menu", HamburgerMenuController)

import GiftRecordsController from "./gift_records_controller"
application.register("gift-records", GiftRecordsController)

import GiftRecordsAutocompleteController from "./gift_records_autocomplete_controller"
application.register("gift-records-autocomplete", GiftRecordsAutocompleteController)

import ShareManagerController from "./share_manager_controller"
application.register("share-manager", ShareManagerController)

import DynamicFilterController from "./dynamic_filter_controller"
application.register("dynamic-filter", DynamicFilterController)

import FavoritesController from "./favorites_controller"
application.register("favorites", FavoritesController)

import EventSelectorController from "./event_selector_controller"
application.register("event-selector", EventSelectorController)

import GiftDateSelectorController from "./gift_date_selector_controller"
application.register("gift-date-selector", GiftDateSelectorController)

import ImagePreviewController from "./image_preview_controller"
application.register("image-preview", ImagePreviewController)

import ImageGalleryController from "./image_gallery_controller"
application.register("image-gallery", ImageGalleryController)

import CommentsController from "./comments_controller"
application.register("comments", CommentsController)

import GiftPersonFormController from "./gift_person_form_controller"
application.register("gift-person-form", GiftPersonFormController)
