:concurrency: 5
:queues:
  - default
:schedule:
  enqueue_due_reminds_job:
    cron: "* * * * *"
    class: "EnqueueDueRemindsJob"
    queue: default
    description: "Enqueue due LINE reminders every minute"
